export const ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST";
export const ADD_SERVICE_REQUEST_SUCCESS ="ADD_SERVICE_REQUEST_SUCCESS";
export const ADD_SERVICE_REQUEST_FAIL="ADD_SERVICE_REQUEST_FAIL";

export const ADMIN_SERVICE_REQUEST="ADMIN_SERVICE_REQUEST";
export const ADMIN_SERVICE_SUCCESS="ADMIN_SERVICE_SUCCESS";
export const ADMIN_SERVICE_FAIL="ADMIN_SERVICE_FAIL";

export const ADMIN_DETAILS_REQUEST="ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS="ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL="ADMIN_DETAILS_FAIL";
